services: 
  mysql:
      image: mysql:8.0
      container_name: example-mysql
      environment:
        MYSQL_DATABASE: 'example'
        MYSQL_ROOT_PASSWORD: paris
      ports:
        - "3306:3306"
      volumes:
        - mysql_data:/var/lib/mysql
        - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      networks:
        - my_network
  
  backend:
    build: ./api
    container_name: example-backend
    environment:
      - DB_USER=root
      - DB_PASSWORD=paris
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=example
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
    networks:
      - my_network
    depends_on:
      - mysql

  frontend:
    build: ./view
    container_name: example-frontend
    ports:
      - "5173:5173"
    networks: 
      - my_network
    depends_on:
      - backend

volumes:
  mysql_data:

networks:
  my_network: