services: 
  mysql:
      image: mysql:8.0
      container_name: example-mysql
      environment:
        MYSQL_DATABASE: 'example'
        MYSQL_ROOT_PASSWORD: paris
      ports:
        - "3306:3306"
      volumes:
        - mysql_data:/var/lib/mysql
        - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      networks:
        - my_network

  frontend:
    build: ./view
    container_name: example-frontend
    ports:
      - "5173:5173"
    networks: 
      - my_network

volumes:
  mysql_data:

networks:
  my_network: