name: Release

on:
  push:
    branches: [main]

release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Check for existing release
        id: check_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          if gh release view "$GITHUB_REF_NAME" --repo "$GITHUB_REPOSITORY" &>/dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Update existing release
        if: steps.check_release.outputs.exists == 'true'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release edit "$GITHUB_REF_NAME"
          --repo "$GITHUB_REPOSITORY"
          --notes "Docker image published to ghcr.io/${{ github.repository }}:${{ github.ref_name }}"

      - name: Create new release
        if: steps.check_release.outputs.exists == 'false'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          "$GITHUB_REF_NAME"
          --repo "$GITHUB_REPOSITORY"
          --notes "Docker image published to ghcr.io/${{ github.repository }}:${{ github.ref_name }}"